(* Parser for block content *)
block = (syntax-in-block / any-char)*

<syntax-in-block> = (image | alias | hashtag | page-link | block-ref | metadata-tag | code-line | youtube | bold | italic | strikethrough | highlight) (* add query later*)
alias = #"\[([\w\s\d]+)\]\(.*?\)"
image = #"!\[(.*?)\]\(.*?\)"
page-link = #"\[\[.*?\]\]"
hashtag = #"\#..*?(?=\s|$)" | #"#\[\[.*?\]\]"
block-ref = #"\(\(([\w\s\d]+)\)\)"
metadata-tag = #"^.+?::"
code-line = #"\`.*?\`"
(* query = #"\{\{query: .*?:.*?\}\}" | #"\{\{[[query]]: .*?:.*?\}\}" *)
youtube = #"\{\{youtube: .*?\}\}" | #"\{\{[[youtube]]: .*?:.*?\}\}"
bold = #"\*\*.*?\*\*"
italic = #"\_\_.*?\_\_"
strikethrough = #"\~\~.*?\~\~"
highlight = #"\^\^.*?\^\^"

any-chars = #'\w+|\W+'
<any-char> = #'\w|\W'