(* Parser for block content *)
block = (syntax-in-block / any-char)*

<syntax-in-block> = (todo | done | image | alias | block-embed | hashtag | page-link | block-ref | metadata-tag | code-line | youtube | bold | italic | strikethrough | highlight | bare-url) (* add query later*)
alias = #"\[(.*?)\]\(.*?\)"
image = #"!\[(.*?)\]\(.*?\)"
page-link = #"\[\[.*?\]\]"
hashtag = #"\#..*?(?=\s|$)" | #"#\[\[.*?\]\]"
block-ref = #"\(\(([\w\s\d]+)\)\)"
metadata-tag = #"^.+?::"
code-line = #"\`.*?\`"
(* query = #"\{\{query: .*?:.*?\}\}" | #"\{\{[[query]]: .*?:.*?\}\}" *)
youtube = #"\{\{youtube: .*?\}\}" | #"\{\{\[\[youtube\]\]: .*?:.*?\}\}"
bold = #"\*\*.*?\*\*"
italic = #"\_\_.*?\_\_"
strikethrough = #"\~\~.*?\~\~"
highlight = #"\^\^.*?\^\^"
todo = #"\{\{\[\[TODO\]\]\}\}"
done = #"\{\{\[\[DONE\]\]\}\}"
block-embed = #"\{\{embed: .*?\}\}" | #"\{\{\[\[embed\]\]: .*?\}\}"
bare-url = #"(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})"

any-chars = #'\w+|\W+'
<any-char> = #'\w|\W'